return {}
--return {
--    "yetone/avante.nvim",
--    event = "VeryLazy",
--    lazy = false,
--    version = false, -- set this if you want to always pull the latest change
--    ---@module 'avante'
--    ---@type avante.Config
--    opts = {
--        provider = "claude",
--        mode = "agentic",
--        auto_suggestions_provider = "gemini",
--        providers = {
--            claude = {
--                endpoint = "https://api.anthropic.com",
--                model = "claude-3-7-sonnet-20250219",
--                extra_request_body = {
--                    temperature = 0.75,
--                    max_tokens = 4096
--                }
--            },
--            xai = {
--                __inherited_from = "gemini",
--                api_key_name = "XAI_API_KEY",
--                endpoint = "https://api.x.ai/v1",
--                model = "grok-4-0709",
--                extra_request_body = {
--                    temperature = 0.7,
--                    max_tokens = 4000,
--                },
--                disable_tools = true
--            },
--            gemini = {
--                model = "gemini-2.5-pro"
--            }
--        }
--    },
--    -- if you want to build from source then do `make BUILD_FROM_SOURCE=true`
--    build = "make",
--    dependencies = {
--        "nvim-treesitter/nvim-treesitter",
--        "stevearc/dressing.nvim",
--        "nvim-lua/plenary.nvim",
--        "MunifTanjim/nui.nvim",
--        --- The below dependencies are optional,
--        "nvim-tree/nvim-web-devicons", -- or echasnovski/mini.icons
--        -- "zbirenbaum/copilot.lua", -- for providers='copilot'
--        {
--            -- support for image pasting
--            "HakonHarnes/img-clip.nvim",
--            event = "VeryLazy",
--            opts = {
--                -- recommended settings
--                default = {
--                    embed_image_as_base64 = false,
--                    prompt_for_file_name = false,
--                    drag_and_drop = {
--                        insert_mode = true,
--                    },
--                    -- required for Windows users
--                    use_absolute_path = true,
--                },
--            },
--        },
--        --{
--        --  -- Make sure to set this up properly if you have lazy=true
--        --  'MeanderingProgrammer/render-markdown.nvim',
--        --  opts = {
--        --    file_types = { "markdown", "Avante" },
--        --  },
--        --  ft = { "markdown", "Avante" },
--        --},
--    },
--}
